ARG version
FROM almalinux:${version:-9}
ARG COURSE=DevOps
ARG TRAINER=Avinash
ENV DURATION=120hrs
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER}, Duration is: ${DURATION}"
CMD ["sleep", "100"]